name:                ECC
version:             0.1.0.0
github:              "githubuser/ECC"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

language: GHC2021
# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ECC#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - bitvec
    - semirings
    - modular-arithmetic
    - random
    - protolude
    - wl-pprint-text
    - vector
    - containers
    - deepseq
    - poly
    - mod
    - MonadRandom
    - QuickCheck
    - bytestring
    - group-theory
    - template-haskell
  default-extensions:
      - DataKinds
      - TypeFamilies 
      - GADTs
      - ScopedTypeVariables
      - UnicodeSyntax
executables:
  ECC-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ECC
    - bitvec

tests:
  ECC-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ECC
